frameworkVersion: ">=2.55.0 <3.0.0"

service: ama-hoi

provider:
  name: aws
  runtime: python3.7
  memorySize: 1024
  region: ${opt:region, 'eu-west-1'}
  stage: dev
  deploymentBucket:
    name: ama-hoi-deployments
    serverSideEncryption: AES256
  deploymentPrefix: deploy
  tags:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
  environment:
    GIT_REV: ${git:branch}:${git:sha1}
    VERSION: ${self:custom.version}
    SERVICE_NAME: ${self:service}
package:
  exclude:
    - '**/*'
  include:
    - lambda_handlers/*.py


functions:
  hello:
    handler: lambda_handlers.handler.hello
    events:
      - http:
          path: ""
          method: "get"
          cors: true

plugins:
  - serverless-plugin-git-variables
  - serverless-deployment-bucket
  - serverless-python-requirements

resources:
  Description: |
    ${self:service} ${git:branch}:${git:sha1}
    ${git:message}

custom:
  version: 0.1.0
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    usePoetry: false
  exportGitVariables: false
